steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'secrets', 'versions', 'access', 'latest',
      '--secret', 'env'
    ]
    id: 'fetch-secret'
    secretEnv: ['ENV_FILE']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/first-project-8101c/cloud-run-source-deploy/soft-engg-project-jan-2025-se-jan-11/team-11-backend-v1',
      '--cache-from', 'us-central1-docker.pkg.dev/first-project-8101c/cloud-run-source-deploy/soft-engg-project-jan-2025-se-jan-11/team-11-backend-v1',
      '--build-arg', 'ENV_FILE=$$ENV_FILE',
      '-f', 'backend/Dockerfile',
      'backend/'  
    ]
    secretEnv: ['ENV_FILE']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/first-project-8101c/cloud-run-source-deploy/soft-engg-project-jan-2025-se-jan-11/team-11-backend-v1'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'team-11-backend-v1',
      '--image', 'us-central1-docker.pkg.dev/first-project-8101c/cloud-run-source-deploy/soft-engg-project-jan-2025-se-jan-11/team-11-backend-v1',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-secrets', 'ENV_FILE=env:latest'
    ]

images:
  - 'us-central1-docker.pkg.dev/first-project-8101c/cloud-run-source-deploy/soft-engg-project-jan-2025-se-jan-11/team-11-backend-v1'

availableSecrets:
  secretManager:
  - versionName: projects/YOUR_PROJECT_ID/secrets/env/versions/latest
    env: 'ENV_FILE'

options:
  logging: CLOUD_LOGGING_ONLY
