import React from 'react';
import {
  Typography,
  Box,
  Card,
  CardContent,
  Grid,
  Avatar,
  Tooltip,
} from '@mui/material';
import AssistantIcon from "@mui/icons-material/Assistant";


const InstructorDashboard = () => {
  // Dummy data for lecture review reports
  const lectureReports = [
    {
      courseName: 'Programming in Python',
      reportSummary: 'Excellent student engagement with a strong understanding of basic syntax. Focus on advanced concepts like decorators and generators is recommended.',
      sentimentScore: 0.85, 
      keyTopics: ['Variables', 'Data Types', 'Functions'],
      suggestedImprovements: ['Incorporate more real-world examples', 'Provide additional exercises on list comprehensions'],
    },
    {
      courseName: 'Machine Learning Practices',
      reportSummary: 'Students are struggling with model selection and hyperparameter tuning. More hands-on practice and detailed explanations are needed.',
      sentimentScore: 0.60, 
      keyTopics: ['Supervised Learning', 'Unsupervised Learning', 'Model Evaluation'],
      suggestedImprovements: ['Provide more guidance on model selection', 'Offer additional resources on hyperparameter tuning'],
    },
    {
      courseName: 'Software Engineering',
      reportSummary: 'Good understanding of software development lifecycle. Emphasize on agile methodologies and testing practices.',
      sentimentScore: 0.75,
      keyTopics: ['SDLC', 'Agile', 'Testing'],
      suggestedImprovements: ['Invite guest speakers from industry', 'Organize a mock project using agile'],
    },
  ];

  return (
    <Box sx={{ maxWidth: '900px', mx: 'auto', p:5 }}>
      <Typography variant="h4" component="h1" fontWeight="bold" marginTop={10} gutterBottom>
        Instructor Dashboard
      </Typography>

      <Typography variant="body1" color="text.secondary" marginBottom={4}>
        Welcome, Instructor! Here are the lecture review reports generated by CogniBot for your courses.
      </Typography>

      <Grid container spacing={3}>
        {lectureReports.map((report, index) => (
          <Grid item xs={12} md={6} key={index}>
            <Card>
              <CardContent>
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 }}>
                  <Typography variant="h6" component="h2" fontWeight="bold">
                    {report.courseName}
                  </Typography>
                  <Tooltip title="Generated using CogniBot AI Agent">
                    
                      <AssistantIcon></AssistantIcon>
                    
                  </Tooltip>
                </Box>

                <Typography variant="body2" color="text.secondary" gutterBottom>
                  {report.reportSummary}
                </Typography>

                <Box sx={{ mt: 2 }}>
                  <Typography variant="subtitle2" fontWeight="bold">
                    Key Topics:
                  </Typography>
                  <ul>
                    {report.keyTopics.map((topic, i) => (
                      <li key={i}>
                        <Typography variant="body2" color="text.secondary">
                          {topic}
                        </Typography>
                      </li>
                    ))}
                  </ul>
                </Box>

                <Box sx={{ mt: 2 }}>
                  <Typography variant="subtitle2" fontWeight="bold">
                    Suggested Improvements:
                  </Typography>
                  <ul>
                    {report.suggestedImprovements.map((improvement, i) => (
                      <li key={i}>
                        <Typography variant="body2" color="text.secondary">
                          {improvement}
                        </Typography>
                      </li>
                    ))}
                  </ul>
                </Box>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>
    </Box>
  );
};

export default InstructorDashboard;